# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
image: Visual Studio 2017

environment:
  DOCKER_PASSWORD:
    secure: ZCFmnM2XKB52rllik1s5OvzxqVvQC8cFmOO5LoT0VPkKnNmkjEtxdt2AlFEORJPw

# scripts that are called at very beginning, before repo cloning
init:
  # This gives the login details for the build instance so you can RDP to it.
  #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - git config --global core.autocrlf input

configuration: Release

# enable service required for build/tests
services:
  - docker

# enable patching of AssemblyInfo.cs files
# assembly_info:
#   patch: true
#   file: '**\AssemblyInfo.*'
#   assembly_version: '{version}'
#   assembly_file_version: '{version}'
#   assembly_informational_version: '{version}'

#---------------------------------#
#       build configuration       #
#---------------------------------#
before_build:
  - docker login appcyc.azurecr.io --username appcyc --password %DOCKER_PASSWORD%
  - docker image list

build_script:
  - docker build -t cbc-identity:%APPVEYOR_BUILD_VERSION% -t appcyc.azurecr.io/cbc-identity:%APPVEYOR_BUILD_VERSION% -t appcyc.azurecr.io/cbc-identity:latest .

after_build:
  - docker push appcyc.azurecr.io/cbc-identity:%APPVEYOR_BUILD_VERSION%
  - docker push appcyc.azurecr.io/cbc-identity:latest
  - docker image list

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

#artifacts:

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#test_script:

#after_test:

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

#---------------------------------#
#        global handlers          #
#---------------------------------#

#on_finish:
#  # This blocks the build server from shutting down giving time to RDP onto it to help with diagnose build issues.
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

  # Slack
  - provider: Slack
    auth_token:
      secure: AkSNuuHmfzAFp2+Oq00NRQFOfrXl4ue08SHx0FC2WTeXSiZv8uVKI3ZBWns7HTcV
    channel: cbc
    on_build_success: false
    on_build_status_changed: true
